---
version: "1"
rules:
  - base: master
    upstream: folio-org:master
    mergeMethod: hardreset
  - base: snapshot
    upstream: folio-org:snapshot
    mergeMethod: hardreset
  - base: q1-2020
    upstream: folio-org:q1-2020
    mergeMethod: hardreset
  - base: q2-2020
    upstream: folio-org:q2-2020
    mergeMethod: hardreset
  - base: q3-2020
    upstream: folio-org:q3-2020
    mergeMethod: hardreset
